### ISSUE TITLE
Prevent "Headers Error" in generated zip files

### ISSUE THREAD

**Issue by Fasguy** [Fasguy/MinecraftToolbox#13]
The zip files i'm generating using fflate in the Toolbox always have header errors. This in itself doesn't appear to be a problem, as all generated zips can still be properly used (at least it seems like that's the case so far). As i'm not exactly sure what kind of problems this _could_ cause, i want to get this fixed sooner, rather than later.

**Comment by 101arrowz** [comment]
Might be this: https://github.com/101arrowz/fflate/discussions/92

**Comment by Fasguy** [comment]
Well, i can certainly say, that i didn't expect to get a response to this problem directly from you.
Anyways, it's nice to know that this doesn't seem to be an actual problem, but rather just a quirk of 7-Zip. Thanks.

**Comment by Fasguy** [comment]
I don't know if my adjustments over time already fixed this issue or if 7-Zip has resolved this on their end. Either way this doesn't appear to be a problem anymore, so i consider this issue fixed.
