### ISSUE TITLE
Connecting to required app resource failed

### ISSUE THREAD

**Issue by DevilishKing658** [Fasguy/MinecraftToolbox#23]
Wont let me generate a seed it keeps saying error
Click to see error details
{
	"headers": {
		"normalizedNames": {},
		"lazyUpdate": null,
		"headers": {}
	},
	"status": 0,
	"statusText": "Unknown Error",
	"url": "/minecraft_toolbox/resources/data/asset_definitions.json",
	"ok": false,
	"name": "HttpErrorResponse",
	"message": "Http failure response for /minecraft_toolbox/resources/data/asset_definitions.json: 0 Unknown Error",
	"error": {
		"isTrusted": true

**Comment by Fasguy** [comment]
A browser addon most likely disallowed the connection to the file.
Please try using a different browser, or try disabling browser addons.

**Comment by Fasguy** [comment]
Closing as stale.
Please re-open if needed.
