### ISSUE TITLE
Suggestion: Add option to save your settings as text or JSON file

### ISSUE THREAD

**Issue by Openstreetmapler** [Fasguy/MinecraftToolbox#29]
When using the loot or recipe randomizer, you can tick or untick every loot/recipe as you want. However, these adjusted settings are gone when reloading the page.

To make this feature _really_ useful, I recommend to add two extra buttons to save and load these adjusted settings (checkmarks) whenever the user wants to.

![Minecraft Randomizer Suggestion](https://user-images.githubusercontent.com/9383930/211391875-2d76e1ff-9ce1-40d5-8ed7-b2c3b93d5929.png)

**Comment by Fasguy** [comment]
This is actually something i've been toying around with in the past. Unfortunately it does bring up a bit of an issue.
When loading the preset in a newer version, what should be state of things that weren't available when the preset was made?

As far as i can see, there are 2 solutions:
* Options that weren't available then keep their default check state
* Options that weren't available then get disabled by default

Of course, regardless of which route i'll take here, there will be a warning message to let people know that things may not work exactly as expected, when loading one of a different version.

**Comment by Openstreetmapler** [comment]
> This is actually something i've been toying around with in the past. Unfortunately it does bring up a bit of an issue. When loading the preset in a newer version, what should be state of things that weren't available when the preset was made?
> 
> As far as i can see, there are 2 solutions:
> 
> * Options that weren't available then keep their default check state
> * Options that weren't available then get disabled by default
> 
> 
> Of course, regardless of which route i'll take here, there will be a warning message to let people know that things may not work exactly as expected, when loading one of a different version.

Your suggestion with the version difference is really good. I suggest that the warning shows old and new game version, followed by all checkboxes that are now different from the loaded preset file. Or even better, highlight all affected checkboxes (e. g. with colored text) in the list directly.

**Comment by Openstreetmapler** [comment]
Thank you so much for implementing! Have an awesome day! 💚
